# Generated by Django 2.2.7 on 2019-11-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(help_text='Obrigatorio preencher o todo', max_length=100)),
                ('done', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now=True)),
                ('closed_at', models.DateTimeField()),
            ],
        ),
    ]
