# Generated by Django 2.2.7 on 2019-11-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0002_auto_20191106_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='done_2',
            field=models.BooleanField(default=False),
        ),
    ]
