# Generated by Django 2.2.7 on 2019-11-14 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0003_todo_done_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='done_2',
            new_name='todo_name',
        ),
    ]
